sudo: false
language: rust
rust:
  - nightly
  - stable
  - beta

# install Coveralls dependencies
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

# Fetch travis-cargo
before_script:
  - |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH

script:
  # build
  - travis-cargo build
  # run the tests
  - travis-cargo test
  # run the benchmarks (pending)
  - travis-cargo bench

after_success:
  # report coverage to coveralls
  - travis-cargo coveralls --no-sudo
  # report coverage to codecov.io
  - bash <(curl https://codecov.io/bash)


before_deploy:
  # build the release executable (for GitHub Releases)
  - travis-cargo build -- --release

# deploy to GitHub Releases
deploy:
  provider: releases
  api_key:
    secure: cl95Vq3ZjOXJyhidhmpb788xajQnnA8czJouKEAb6MQKVvR4ikwY4+pe0TFgLwuMIFDFviUgkgRbQ7wLX2FP/LMilBpRN+IFfb49wRvR547gDe2yjqqocudzh6KdDMhubjg/jSVC5VzAnX8fEkOckezZl/+352gFtIasPzFDQEo+5Z3Ny4Wa9Xwu38W/en7A5jU3Z4rxvh71mlRd+BAvzkP6aqFYfmQTL9cS2Juo5roi+odg1hCsosXsJu/uhewYSYXMkHguSjho1Ulm9Sz5fL5R9yhKaxzm5jnWFt5PetaBjSyDcuVSYwhWoupsStJLcb0+e9bgj7vddEECOGMdKaJ2Mp1psr/3mzdFzoMvE70sPtA8V7urIwCgsy9UbR1EzMuFJayJDYwDPOMJYVsGn85gpZn32qY7osXlrczBd/xms+67AWJSceYYfh3HHjPxwYoj469Wg1VVgAS/co4Lgxq3AnWRDMTFVtZioRsE7SnBnjwzNppr6XLY0HfcgM+GJ2aCvBVmHRLd9hEA7KVbOEgYpOLSJj/NP8YOmXGm4T5LOuShN9Yv8+eojl7vHMHqfWt0YkMYsuBhnGIYaYqCetBUwcNyCNQ+PVj+NOixVcG3nslBZK1QGFlWn4W753h0FeYwFLc3F3AhdlCUgvohnAsGbOiQNJ1Q4GEnywu8tQc=
  file: target/release/liblin.rlib
  on:
    rust: nightly
    repo: hawkw/lin
    tags: true

# triggers only if we're doing a deploy (tagged version)
# deploy triggers only on the nightly build
after_deploy:
  # build the rustdoc & upload to GitHub Pages
  - travis-cargo doc && travis-cargo doc-upload
  # package for crates.io deployment and publish
  - |
    travis-cargo package &&
    travis-cargo publish -- --token $CRATES_TOKEN

env:
  global:
    - secure: JdkRzYx6/1GhS10WnjtAikjPXCpkqBkaHYvhO16hhnbzaAMOmocNHxoNBpqU2uPfcnRRNH/4N6PgPRwyafVkyPkKMXFeuhxVs7DrtyrRY9CyrwPgTVHZ9NxIbTfrcfecUamPJOVrwxZsQphAwsf5stA3Mm11aNlyf7OZ81qH8Xv+63bWf9knLAdXb7nwCWXXzyI5K58sz3N4APCSbpazw1QLndhghflGjXQMGsJCW9cS1cvTImXkwkBTCLv1Pq5NgozkWXwjJwo+mPjlH+PX34TkrPnoYBSpjlgYgZBln9dSXRE79bPu5shc2Iky2kYKFoTuxJbAhhrnM0IiRT9mlRMvE2JL5XJwoBrjJFMDL3bjVfwkwuHfnHjKAB8MHZ4Wf0tWtJ6lngTovSO6sFiHrX7eBi8el8Af+bliPc5zKsXFiYwC3L2uvcKtqDm+jZKcemEqfl3XCCmCQ0ziq0GdHYe54U7Q08kD8UCU3owEeQF18W3wDTs9VAAbHYGXIf1Nv8/jFjzVay5XPkn4tQeM6M6wFvpi6+CwyWtJ0z9yPp9YeOaVWwV96tRJzW5cNw/Pm5InNpGcZWpmm8+tkio4sgl6WtQBbQKdG57AgTTt2YyEzLNVdzeK7rqSTpTAvQKTWYbckXpl+4ZJ38J7Mg2nwxd2Fks0LYiz2CyK3OrjDbg=
    - secure: d8z06cQ9DfWals4rOodH9VNIYMgW+cW6yWko4E1aBSWS+FMOr77kjlriaXsgUWu7rHo+KTMQw6enikuu2Ti/N/X/L2kuSEp04dowv6adarkZcGH0+a3rNR+wRr8rGf4/oVv6Ir3PP3XXkWgdQu3d0vG4fNjonUIshSJK0KcC+Q/c7Kg0lfeFCo4KzlanQO33JgU6Yi84UdZ4auuriLims+LvJ9sGNkIKFkVYZfuc2P8GLV0uCcEFgiet8mxXeV/XJLUzqNOBOi9N0WALcMyffFgbTXsnDMvK+tiHXd9IaKVDsb2kYcMNsmGAC2TUsBLQr1HashfQO1sD3wANS1uJ8g21ulE9CtKkcFq9V7srCDpGe1uGQ23nCu3inmFjVZm0UGspxH6FTXZP7lFZ6whCJQE6Y36SddieyF6D39kCUmuVA7J7TsLHj+1CKoSqWhJu13ql7mqds458S1FFn0mcXpNJ314kvXc63nU/+HSothAE2vN841b6KQAL+Z5WDQ1yozSgQ8/u+3KTGoKX4qMPiSiOASU5bVgnUFT7XhxIEBMkCeTTzlsNXrhf/c3jQKJgO4fNw1P7rAyLY1RGoyUVL9+yhHkg3WXfsEVxKgQ+Xj/amW6CGkx7P6jgVpE7Zfq8yFNKAYzQuKbYT9iTV/X8nwlQUYyKkvqbiO4h1exNdic=
